version: '3.8'
services:
  hos-enterprise:
    image: hos-enterprise:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_VERSION=${APP_VERSION:-latest}
        - BASE_URL=${BASE_URL:-/op}
        - API_URL=${API_URL:-/}
    ports:
      - '80:80'
